package app.pay.panda.retrofit


object Constant {


    const val MERCHANT_CODE="merchant_Code"
    const val FROM = "from"
    const val TPINSTATUS = "tpinstatus"
    const val MainBase_URL = "https://devapi.paypandabnk.com/"
    const val MainBase_URL_2 = "https://cloud.yoopay.in/"
    const val Image_Base_URL = "https://api.yoopay.in/img/"
    const val PIMAGE_URL="https://api.paypandabnk.com/api/cloudinary/"
    const val PREFER_NAME = "PayPanda"
    const val IS_USER_LOGIN = "is_user_login"
    const val NAME = "name"
    const val EMAIL = "user_email"
    const val MOBILE = "user_mobile"
    const val BUSINESS_NAME = "business_name"
    const val PROFILE_PIC = "user_profile"
    const val USER_TYPE = "user_type"
    const val USER_TYPE_ID = "user_type_id"
    const val USER_ID = "userID"
    const val SHOP_NAME = "shop_name"
    const val ADMIN_MOBILE = "admin_mobile"
    const val ADMIN_WHATSAPP = "admin_whatsapp"
    const val ADMIN_EMAIL = "admin_email"
    const val BALANCE_LIMIT = "balance_limit"
    const val FCM_UPDATED = "fcm_updated"
    const val IS_LANGUAGE_SELECTED = "is_language_selected"
    const val M_LAT = "mlat"
    const val M_LONG = "mlong"
    const val ADHAAR_VERIFIED = "adhaarVerified"
    const val PAN_VERIFIED = "panVerified"
    const val IDENTITY_VERIFIED = "isIdentity_verified"
    const val IS_GST = "is_gst"
    const val GST_AVAILABLE = "isGstAvailable"
    const val PAN_NAME = "pan_name"
    const val PAN_NUMBER = "pan_number"
    const val ISBANK = "is_bank"
    const val ISDOCS = "is_document"
    const val ISVIDEO = "is_kycVid"
    const val ISPERSONALDETAILS = "is_personalDetails"
    const val ISSELFDECLARE = "is_self_declare"
    const val ISAPPROVED = "is_approved"
    const val MAIN_WALET = "main_wallet"
    const val AEPS_WALLET = "aeps_wallet"
    const val COMMISSION_WALLET = "commission_wallet"
    const val USER_TOKEN = "user_token"
    const val LOGIN_STEPS = "login_steps"
    const val CASHBACK_WALLET = "cashback_wallet"
    const val VERIFICATION_CHARGE="verification_charge"
    const val DEVICE_NAME="device_name"
    const val SCANNER_PACKAGE="scanner_package"
    const val SCANNER_IMAGE="scanner_image"
    const val NOTIFICATION_COUNT="notification_count"
    const val RUPEE="\u20B9"
    const val USERTYPE="user_type"
    const val ID="ID"
}
